function [paramS,shiftS] = getInputs(inputS)
% Function to generate patient & shift parameter dictionaries from 
% input structure (inputS), generated by reading .txt parameter file.
% See ReadDCEParameterFile.m for more details.
%
% AI 5/26/16
% ----------------------------------------------------------------------------------------------------

%Define default values
if ~isfield(inputS,'cutOff') | isempty(inputS.cutOff)
    cutOff = 0; % Default r-squared cutoff for maps
else
    cutOff = inputS.cutOff;
end
patInC = {'model','saveMatPlot','writeDelim','filt'...
          'cAgent','T1Map','displayImgNum','CACut','cutOff'};
defOptC = {'ET','n','y','n','mh',0,50,0.1,cutOff};
shiftInC = {'checkShift','checkAIFShift','ROIPointShift','userAIFShift','skip','FAF'};
defShiftC = {'y','y',0,0,0,1};


%Create patient parameter dictionary
inFieldsC = fieldnames(inputS);
if isempty(inFieldsC)
    error('Invalid parameter file input');
else
    [~,inIdx] = ismember(patInC,inFieldsC);
    missingInV = ~inIdx;
    missingInV = find(missingInV);
    % Copy input parameters
    paramS = inputS;
    % Fill missing parameters with default options
    for k = 1:numel(missingInV)
        paramS.(patInC{missingInV(k)}) = defOptC{missingInV(k)};
    end
end

%Create shift parameter dictionary
[~,inIdx] = ismember(shiftInC,inFieldsC);
missingInV = ~inIdx;
missingInV = find(missingInV);
% Copy input parameters
shiftS = inputS;
% Fill missing parameters with default options
for k = 1:numel(missingInV)
    shiftS.(shiftInC{missingInV(k)}) = defShiftC{missingInV(k)};
end


end