function [newdata] = dicomrt_getcontourcdata(data)
% dicomrt_getcontourcdata(data)
%
% Retrieve coordinate data generated by contourc.
%
% See also: contourc
%
% Copyright (C) 2002 Emiliano Spezi (emiliano.spezi@physics.org) 

% scan and plot data
start=1;
highestpair=0;
newdata=[];
while (length(data)-highestpair)~=0
    npair=data(2,start);
    lowestpair=start+1;
    highestpair=start+npair;
    data2add=vertcat(data(1,lowestpair:highestpair), data(2,lowestpair:highestpair))';
    newdata=vertcat(newdata,data2add);
    start=highestpair+1;
end

