function tagMapS = initTagMapS()
%function tagMapS = initializeTagMapS
%This function initializes structures which are used to parse the AAPM/RTOG format
%and set up the CERR entries.
%
%Author: J. O. Deasy, deasy@radonc.wustl.edu
%
%Rerences:
%1.  W. Harms, Specifications for Tape/Network Format for Exchange of Treatment Planning Information,
%    version 3.22., RTOG 3D QA Center, (http://rtog3dqa.wustl.edu), 1997.
%2.  J.O. Deasy, "A tool for distributing treatment planning software developments:
%    the Radiotherapy Toolbox for Matlab," Submitted for publication to Med Phys, Dec. 2001.
%
%Last Modified:  8 Mar 02, by JOD.
%
% Copyright 2010, Joseph O. Deasy, on behalf of the CERR development team.
% 
% This file is part of The Computational Environment for Radiotherapy Research (CERR).
% 
% CERR development has been led by:  Aditya Apte, Divya Khullar, James Alaly, and Joseph O. Deasy.
% 
% CERR has been financially supported by the US National Institutes of Health under multiple grants.
% 
% CERR is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of CERR is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% CERR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with CERR.  If not, see <http://www.gnu.org/licenses/>.


tagMapS = struct( ...
'TAPESTANDARD',                   'tapeStandardNumber'       ,...
'TAPESTANDARDNUMBER',             'tapeStandardNumber'       ,...
'INTERCOMPARISONSTANDARD',        'intercomparisonStandard'  ,...
'INTERCOMPARISONSTANDARDNUMBER',  'intercomparisonStandard'  ,...
'INSTITUTION',                    'institution'              ,...
'DATECREATED',                    'dateCreated'             ,...
'IMAGENUMBER'              ,       'imageNumber'           , ...
'IMAGE'                    ,       'imageNumber'           , ...
'IMAGETYPE'                ,       'imageType'             , ...
'CASENUMBER'               ,       'caseNumber'            , ...
'CASE'                     ,       'caseNumber'            , ...
'PATIENTNAME'             ,       'patientName'           , ...
'WRITER'                  ,       'writer'                , ...
'COMMENTDESCRIPTION'      ,       'commentDescription'    , ...
'DATEWRITTEN'             ,       'dateWritten'           , ...
'FILEOFORIGIN'            ,       'fileOfOrigin'          , ...
'UNITNUMBER'              ,       'unitNumber'            , ...
'SCANTYPE'                 ,      'scanType'              , ...
'CTOFFSET'                 ,      'CTOffset'              , ...
'GRID1UNITS'               ,      'grid1Units'            , ...
'GRID2UNITS'               ,      'grid2Units'            , ...
'NUMBERREPRESENTATION'     ,      'numberRepresentation'  , ...
'BYTESPERPIXEL'            ,      'bytesPerPixel'         , ...
'NUMBEROFDIMENSIONS'       ,      'numberOfDimensions'    , ...
'SIZEOFDIMENSION1'         ,      'sizeOfDimension1'      , ...
'SIZEOFDIMENSION2'         ,      'sizeOfDimension2'      , ...
'ZVALUE'                   ,      'zValue'                , ...
'XOFFSET'                  ,      'xOffset'               , ...
'YOFFSET'                  ,      'yOffset'               , ...
'CTAIR'                    ,      'CTAir'                 , ...
'CTWATER'                  ,      'CTWater'               , ...
'SLICETHICKNESS'           ,      'sliceThickness'        , ...
'SITEOFINTEREST'           ,      'siteOfInterest'        , ...
'SCANDESCRIPTION'          ,      'scanDescription'       , ...
'SCANNERTYPE'              ,      'scannerType'           , ...
'SCANFILENAME'             ,      'scanFileName'          , ...
'HEADINOUT'                ,      'headInOut'             , ...
'POSITIONINSCAN'           ,      'positionInScan'        , ...
'PATIENTATTITUDE'          ,      'patientAttitude'       , ...
'TAPEOFORIGIN'             ,      'tapeOfOrigin'          , ...
'STUDYNUMBEROFORIGIN'      ,      'studyNumberOfOrigin'   , ...
'SCANID'                   ,      'scanID'                , ...
'SCANNUMBER'               ,      'scanNumber'            , ...
'SCANDATE'                 ,      'scanDate'              , ...
'CTSCALE'                  ,      'CTScale'               , ...
'DISTRUSTABOVE'            ,      'distrustAbove'         , ...
'IMAGESOURCE'              ,      'imageSource'           , ...
'STRUCTURENAME'             ,     'structureName'         , ...
'STRUCTUREFORMAT'           ,     'structureFormat'       , ...
'NUMBEROFSCANS'             ,     'numberOfScans'         , ...
'MAXIMUMSCANS'              ,     'maximumNumberScans'    , ...
'MAXIMUMNUMBERSCANS'        ,     'maximumNumberScans'    , ...
'MAXIMUMPOINTSPERSEGMENT'   ,     'maximumPointsPerSegment', ...
'MAXIMUMSEGMENTSPERSCAN'    ,     'maximumSegmentsPerScan', ...
'STRUCTUREEDITION'          ,     'structureEdition'      , ...
'STRUCTURECOLOR'            ,     'structureColor'        , ...
'STRUCTUREDESCRIPTION'      ,     'structureDescription'  , ...
'BEAMNUMBER'                 ,    'beamNumber'            , ...
'BEAM'                       ,    'beamNumber'            , ...
'BEAMMODALITY'               ,    'beamModality'          , ...
'BEAMENERGYMEV'              ,     'beamEnergyMeV'         , ...
'BEAMDESCRIPTION'            ,    'beamDescription'       , ...
'RXDOSEPERTXGY'              ,     'RxDosePerTxGy'         , ...
'MONITORUNITSPERTX'          ,    'MonitorUnitsPerTx'      , ...  %KU added 7Oct07
'NUMBEROFTX'                 ,    'numberOfTx'            , ...
'FRACTIONGROUPID'            ,    'fractionGroupID'       , ...
'BEAMTYPE'                   ,    'beamType'              , ...
'PLANIDOFORIGIN'             ,    'planIDOfOrigin'        , ...
'PLANOFORIGIN'               ,    'planIDOfOrigin'        , ...   %misnomer in TMS V.6 output
'COLLIMATORTYPE'             ,    'collimatorType'        , ...
'APERTURETYPE'               ,    'apertureType'          , ...
'APERTUREDESCRIPTION'        ,    'apertureDescription'   , ...
'COLLIMATORANGLE'            ,    'collimatorAngle'       , ...
'GANTRYANGLE'                ,    'gantryAngle'           , ...
'COUCHANGLE'                 ,    'couchAngle'            , ...
'NOMINALISOCENTERDISTANCE'   ,    'nominalIsocenterDistance', ...
'NOMINALISOCENTERDIST'       ,    'nominalIsocenterDistance', ...  %Found this variant spelling
'APERTUREID'                 ,    'apertureID'            , ...
'WEDGEANGLE'                 ,    'wedgeAngle'            , ...
'WEDGEROTATIONANGLE'         ,    'wedgeRotationAngle'    , ...
'ARCANGLE'                   ,    'arcAngle'              , ...
'MACHINEID'                  ,    'machineID'             , ...
'BEAMWEIGHT'                 ,    'beamWeight'            , ...
'WEIGHTUNITS'                ,    'weightUnits'           , ...
'COMPENSATOR'                ,    'compensator'           , ...
'COMPENSATORFORMAT'          ,    'compensatorFormat'     , ...
'FILMNUMBER'                 ,    'filmNumber'            , ...
'FILMDATE'                   ,    'filmDate'              , ...
'FILMTYPE'                   ,    'filmType'              , ...
'FILMSOURCE'                 ,    'filmSource'            , ...
'SOURCEIMAGEDISTANCE'        ,    'sourceImageDistance'   , ...
'FILMDESCRIPTION'            ,    'filmDescription'       , ...
'ODSCALE'                    ,    'ODScale'               , ...
'BITSPERPIXEL'               ,    'bitsPerPixel'          , ...
'DOSENUMBER'                 ,    'doseNumber'            , ...
'DOSE'                       ,    'doseNumber'            , ...
'DOSETYPE'                   ,    'doseType'              , ...
'DOSEUNITS'                  ,    'doseUnits'             , ...
'DOSESCALE'                  ,    'doseScale'             , ...
'ORIENTATIONOFDOSE'          ,    'orientationOfDose'     , ...
'SIZEOFDIMENSION3'           ,    'sizeOfDimension3'      , ...
'COORD1OFFIRSTPOINT'         ,    'coord1OFFirstPoint'    , ...
'COORD2OFFIRSTPOINT'         ,    'coord2OFFirstPoint'    , ...
'HORIZONTALGRIDINTERVAL'     ,    'horizontalGridInterval', ...
'VERTICALGRIDINTERVAL'       ,    'verticalGridInterval'  , ...
'DOSEDESCRIPTION'            ,    'doseDescription'       , ...
'DOSEEDITION'                ,    'doseEdition'           , ...
'PLANNUMBEROFORIGIN'         ,    'planNumberOfOrigin'    , ...
'PLANEDITIONOFORIGIN'       ,     'planEditionOfOrigin'   , ...
'VERSIONNUMBEROFPROGRAM'     ,    'versionNumberOfProgram', ...
'XCOORDOFNORMALIZNPOINT'     ,    'xcoordOfNormaliznPoint', ...
'YCOORDOFNORMALIZNPOINT'     ,    'ycoordOfNormaliznPoint', ...
'ZCOORDOFNORMALIZNPOINT'     ,    'zcoordOfNormaliznPoint', ...
'DOSEATNORMALIZNPOINT'       ,    'doseAtNormaliznPoint'  , ...
'DOSEERROR'                  ,    'doseError'             , ...
'COORD3OFFIRSTPOINT'         ,    'coord3OfFirstPoint'    , ...
'DEPTHGRIDINTERVAL'          ,    'depthGridInterval'     , ...
'VOLUMETYPE'                 ,    'volumeType'            , ...
'NUMBEROFPAIRS'              ,    'numberOfPairs'         , ...
'MAXIMUMNUMBERPAIRS'         ,    'maximumNumberPairs'    , ...
'MAXIMUMPAIRS'               ,    'maximumNumberPairs'    , ...
'VOLUMESCALE'                ,    'volumeScale'           , ...
'DATEOFDVH'                  ,    'dateOfDVH'             , ...
'SEEDMODEL'                  ,    'seedModel'             , ...
'ISOTOPE'                    ,    'isotope'               , ...
'SEEDSTRENGTH'               ,    'seedStrength'          , ...
'STRENGTHUNITS'              ,    'strengthUnits'         , ...
'DATEOFIMPLANT'              ,    'dateOfImplant'         , ...
'NUMBEROFSEEDS'              ,    'numberOfSeeds'         , ...
'ORIENTATIONOFSTRUCTURE'     ,    'orientationOfStructure');         %Added for Maryland dataset compatibility

