function ROIInterpretedType = initROIInterpretedType
% ROIInterpretedType
%       Written DK Sept-2009  
% 
% 
% This function lists in alphabetical order ROIInterpretedType as per DICOM PS 3.3 - 2008
% Page 519. 
%
% Copyright 2010, Joseph O. Deasy, on behalf of the CERR development team.
% 
% This file is part of The Computational Environment for Radiotherapy Research (CERR).
% 
% CERR development has been led by:  Aditya Apte, Divya Khullar, James Alaly, and Joseph O. Deasy.
% 
% CERR has been financially supported by the US National Institutes of Health under multiple grants.
% 
% CERR is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of CERR is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% CERR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with CERR.  If not, see <http://www.gnu.org/licenses/>.

ROIInterpretedType = struct(...
    'AVOIDANCE'                                  ,  'region in which dose is to be minimized',... 
    'BOLUS'                                          ,  'patient bolus to be used for external beam therapy',... 
    'BRACHY_ACCESSORY'                    ,  'brachytherapy accessory device',... 
    'BRACHY_CHANNEL'                       ,  'brachytherapy channel',... 
    'BRACHY_CHNL_SHLD'                   ,  'brachytherapy channel shield',... 
    'BRACHY_SRC_APP'                        ,  'brachytherapy source applicator',... 
    'CAVITY'                                         ,  'patient anatomical cavity',... 
    'CONTRAST_AGENT'                       ,  'volume into which a contrast agent has been injected',... 
    'CONTROL'                                     ,  'ROI to be used in control of dose optimization and calculation',...
    'CTV'                                              ,  'Clinical Target Volume (as defined in ICRU50)',... 
    'DOSE_REGION'                             ,  'ROI to be used as a dose reference',... 
    'EXTERNAL'                                    ,  'external patient contour',... 
    'FIXATION'                                     ,  'external patient fixation or immobilisation device',... 
    'GTV'                                              ,  'Gross Tumor Volume (as defined in ICRU50)',... 
    'IRRAD_VOLUME'                            ,  'Irradiated Volume (as defined in ICRU50)',... 
    'ISOCENTER'                                  ,  'treatment isocenter to be used for external beam therapy',... 
    'MARKER'                                       ,  'patient marker or marker on a localizer',... 
    'ORGAN'                                         ,  'patient organ',... 
    'PTV'                                               ,  'Planning Target Volume (as defined in ICRU50)',... 
    'REGISTRATION'                             ,  'registration ROI',... 
    'SUPPORT'                                      ,  'external patient support device',...  
    'TREATED_VOLUME'                        ,  'Treated Volume (as defined in ICRU50)'... 
);


