#include "test_circshift.c"
#include "test_dgt_fb.c"
#include "test_idgt_fb.c"
#include "test_dgt_long.c"
#include "test_idgt_long.c"
#include "test_fftshift.c"
#include "test_ifftshift.c"
#include "test_fir2long.c"
#include "test_long2fir.c"
#include "test_normalize.c"
#include "test_firwin.c"
#include "test_gabdual_painless.c"
#include "test_gabdual_long.c"

