function testSegContainers
% test calls to models in multiple container
%
% APA, 03/30/2020

algorithm = ['CT_ChewingStructures_DeepLabV3^',...
            'CT_Larynx_DeepLabV3^',...
            'CT_PharyngealConstrictor_DeepLabV3^',...
            'CT_HeadAndNeck_SelfAttention'];
container_dir = ...
    ['/cluster/home/clinSegData/container_builds/CT_SwallowingAndChewing_DeepLabV3/SwallowingAndChewing_CPUandGPU_nopkill.sif^',...
    '/cluster/home/clinSegData/container_builds/CT_SwallowingAndChewing_DeepLabV3/SwallowingAndChewing_CPUandGPU_nopkill.sif^',...
    '/cluster/home/clinSegData/container_builds/CT_SwallowingAndChewing_DeepLabV3/SwallowingAndChewing_CPUandGPU_nopkill.sif^',...
    '/cluster/home/singularity_cache/hn_test_apa_no_pkill.sif'];
inputDicomPath = '/cluster/home/clinSegData/container_builds/CT_SwallowingAndChewing_DeepLabV3/sample_data';
outputDicomPath = '/cluster/home/aptea/segSessions';
sessionPath = '/cluster/home/aptea/segSessions';
savePlanc = 'No';
runSegClinic(inputDicomPath,outputDicomPath,...
    sessionPath,algorithm,savePlanc,container_dir)

