function createUIControlsROE(hFig,planC)
% createUIControlsROE.m
% Create UI controls for the ROE interface.
% AI 10/21/21

global stateS

ud = guidata(hFig);

% Get GUI size, margins
leftMarginWidth = stateS.leftMarginWidth;
topMarginHeight = stateS.topMarginHeight;
pos = get(hFig,'Position');
GUIWidth = pos(3);
GUIHeight = pos(4);
shift = 10;
defaultColor = [0.8 0.9 0.9];
figColor = [.6 .75 .75];
posTop = GUIHeight-topMarginHeight;


%Draw frames
inputH(1) = uicontrol(hFig,'tag','titleFrame','units','pixels',...
    'Position',[shift shift leftMarginWidth+.12*GUIWidth,...
    GUIHeight-topMarginHeight-4.8*shift ],'Style','frame',...
    'backgroundColor',defaultColor);
inputH(2) = axes('parent',hFig,'units','pixels','Position',...
    [leftMarginWidth+.13*GUIWidth shift GUIWidth-leftMarginWidth-.14*GUIWidth...
    GUIHeight-topMarginHeight-1.2*shift ],'color',defaultColor,'ytick',[],...
    'xtick',[],'box','on');

%Create tabs
inputH(3) = uicontrol(hFig,'style','togglebutton','string','Settings',...
    'units','pixels','position',[1.1*shift GUIHeight-...
    topMarginHeight-3.9*shift 8*shift 3.5*shift],'fontWeight','bold',...
    'fontSize',10,'BackgroundColor',defaultColor,'foregroundColor',...
    [0 0 0],'HorizontalAlignment','left','callback',...
    @(hObj,hData)switchTabsROE(hObj,hData,hFig));

inputH(4) = uicontrol(hFig,'style','togglebutton','string','Constraints',...
    'units','pixels','position',[9.2*shift GUIHeight-...
    topMarginHeight-3.9*shift 8*shift 3.5*shift],'fontWeight','bold',...
    'fontSize',10,'BackgroundColor',[211 228 228]./255,'foregroundColor',...
    [0.5 0.5 0.5],'HorizontalAlignment','left','callback',...
    @(hObj,hData)switchTabsROE(hObj,hData,hFig));

inputH(5) = uicontrol(hFig,'units','pixels',...
    'Position',[17.25*shift GUIHeight-topMarginHeight-3.9*shift 34.2*shift,...
    3.6*shift],'Style','push','backgroundColor',figColor,'enable','off');


%% ------- TAB-1: SETTINGS----------------------

%Display models for selected protocol
tab1ControlsH(1) = uicontrol(hFig,'tag','modelTitle','units','pixels',...
    'Position',[2*shift posTop-.16*GUIHeight .16*GUIWidth 2*shift],...
    'String','','Style','text','fontSize',9, 'fontWeight', 'Bold',...
    'BackgroundColor',defaultColor,'HorizontalAlignment','left');
optS = opts4Exe('CERRoptions.json');
protPath = optS.ROEProtocolPath;
if contains(protPath,'getCERRPath')
    protPath = eval(protPath);
end
tab1ControlsH(2) = uicontrol(hFig,'tag','modelFileSelect','units','pixels',...
    'Position',[2*shift posTop-.12*GUIHeight .16*GUIWidth 3*shift], 'String',...
    'Select baseline fractionation','Style','push', 'fontSize',10,...
    'FontWeight','normal','BackgroundColor',defaultColor,...
    'HorizontalAlignment','right','callback','ROE(''LOAD_MODELS'')',...
    'tooltip',sprintf(['Push to select fractionation schedule.\n ',...
    'Reading from ',protPath,'.\n To read from a different location',...
    ', update ROEProtocolPath in CERRoptions.json']));


% Pop-up menus to select structures & dose plans
tablePosV = [.22*GUIWidth-2.5*shift posTop-.13*GUIHeight .22*GUIWidth 2.4*shift];
colWidth = tablePosV(3)/2-1;
tab1ControlsH(3) = uitable(hFig,'Tag','strSel','Position',tablePosV-...
    [0 2.5*shift 0 0],'Enable','Off','ColumnName',[],'RowName',[],...
    'Visible','Off','backgroundColor',defaultColor,'columnEditable',...
    [true,true],'Data',{'Select structure','List of structures'},...
    'ColumnWidth',{colWidth,colWidth},'FontSize',10,...
    'cellEditCallback',@(hObj,hData)editParamsROE(hObj,hData,hFig,planC));
tab1ControlsH(4) = uitable(hFig,'Tag','doseSel','Position',tablePosV,...
    'Enable','Off','ColumnName',[],'RowName',[],'Visible','Off',...
    'backgroundColor',defaultColor,'columnEditable',[true,true],...
    'Data',{'Select dose plan','List of plans'},'ColumnWidth',...
    {colWidth,colWidth},'FontSize',10,'cellEditCallback',...
    @(hObj,hData)editParamsROE(hObj,hData,hFig,planC));

% Tables to display & edit model parameters
%Title: Model parameters
tab1ControlsH(5) = uicontrol(hFig,'units','pixels','Visible','Off',...
    'fontSize',10,'Position',tablePosV + [0 -.1*GUIHeight 0 0 ],...
    'String','Model parameters','Style','text','FontWeight','Bold',...
    'HorizontalAlignment','Left','backgroundColor',defaultColor);  
%Model name display
tab1ControlsH(6) = uicontrol(hFig,'units','pixels','Visible','Off','String','',...
    'Position',tablePosV + [0 -.15*GUIHeight 0 10 ],'FontSize',9,...
    'Style','text','FontWeight','Bold','HorizontalAlignment','Left',...
    'backgroundColor',defaultColor,'foregroundColor',[.6 0 0]);    
%JSON content display table (temp decomissioned)
tab1ControlsH(7) = uitable(hFig,'Tag','fieldEdit','Position',tablePosV + ...
    [0 -.73*GUIHeight 0 8*shift],'Enable','Off',...
    'ColumnName',{'Fields','Values'},'FontSize',10,'RowName',[],...
    'Visible','Off','backgroundColor',defaultColor,...
    'ColumnWidth',{round(tablePosV(3)/2),round(tablePosV(3)/2)},...
    'columnEditable',[false,true],'backgroundcolor',[1 1 1],...
    'cellEditCallback',@(hObj,hData)editParamsROE(hObj,hData,hFig,planC)); 

% Push-buttons to save, plot, display style
%Save button
tab1ControlsH(8) = uicontrol(hFig,'units','pixels','Tag','saveJson',...
    'Position',[.36*GUIWidth 1.5*shift .06*GUIWidth 3*shift],...
    'backgroundColor',defaultColor,'String','Save','Style','Push',...
    'fontSize',10,'FontWeight','normal','Enable','Off',...
    'Callback','ROE(''SAVE_MODELS'' )','tooltip','Save changes to JSON');
%Plot button
tab1ControlsH(9) = uicontrol(hFig,'units','pixels','Tag','plotButton',...
    'Position',[.29*GUIWidth 1.5*shift .06*GUIWidth 3*shift],...
    'backgroundColor',defaultColor,'String','Plot','Style','Push',...
    'fontSize',10,'FontWeight','normal','Enable','Off',...
    'Callback','ROE(''PLOT_MODELS'' )','tooltip','Push to plot');  
%Plot mode
tab1ControlsH(10) = uicontrol(hFig,'units','pixels','Tag','switchPlot',...
    'Position',[.18*GUIWidth .1*shift .1*GUIWidth 4*shift],...
    'backgroundColor',[1 1 1],'String',{'--Display mode--',...
    'NTCP v.BED','NTCP v.TCP','Scale fraction size',...
    'Scale no. fractions' },'Style','popup', 'fontSize',10,...
    'FontWeight','normal','Enable','On','Callback',@(hObj,hEvt)...
    setPlotModeROE(hObj,hEvt,hFig),'tooltip','Select plot axes.'); 

% Input prescribed dose
tab1ControlsH(11) = uicontrol('parent',hFig,'units','pixels','Position',...
    [.22*GUIWidth-2*shift posTop-.09*GUIHeight 10*shift,2*shift],...
    'Style','Text','String','Prescribed Dose','fontSize',10,...
    'backgroundColor',defaultColor);
tab1ControlsH(12) = uicontrol('parent',hFig,'units','pixels','Position',...
    [.3*GUIWidth+2*shift posTop-.09*GUIHeight 8*shift,2.5*shift],...
    'Style','Edit','String','','Visible','On','fontSize',10,...
    'Callback',@(hObj,hEvt)clearStoredDVHsROE(hObj,hEvt,hFig),...
    'tooltip','Input Rx (Gy) and press enter.');
tab1ControlsH(13) = uicontrol('parent',hFig,'units','pixels','Position',...
    [.38*GUIWidth+shift posTop-.09*GUIHeight 2*shift,2*shift],'Style',...
    'Text','String','Gy','fontSize',10,'backgroundColor',defaultColor);


%% ------------------------ TAB-2: CONSTRAINTS ---------------------------

% Buttons (prev/next) to view constraints in order of violation
titlePosV = [.14*GUIWidth posTop-15*shift 20*shift 2.4*shift];

tab2ControlsH(1) = uicontrol(hFig,'units','pixels',...
    'Position',titlePosV,'Style', 'text','string','View previous / next',...
    'FontSize',11,'backgroundColor',defaultColor,...
    'Visible','Off');
tab2ControlsH(2) = uicontrol(hFig,'units','pixels',...
    'Position',titlePosV-[0 0 18*shift 0],'Style','push','string',...
    '<<','FontSize',12,'FontWeight','Bold','backgroundColor',defaultColor,...
    'callback',{@dispCriteriaROE,hFig,'prev'}','Visible','Off');
tab2ControlsH(3) = uicontrol(hFig,'units','pixels',...
    'Position',titlePosV-[-18*shift 0 18*shift 0],'Style','push','string',...
    '>>','FontSize',12,'FontWeight','Bold','backgroundColor',defaultColor,...
    'callback',{@dispCriteriaROE,hFig,'next'}','Visible','Off');
tab2ControlsH(4) = uicontrol(hFig,'units','pixels',...
    'Position',titlePosV-[2*shift -5*shift -5*shift 0],'Style', 'text',...
    'string','Select constraints to display','FontSize',11,...
    'FontWeight','Bold','backgroundColor',defaultColor,'Visible','Off');

%Table for interactive selection of constraints to display
tableWidth = 0.4*GUIWidth;
tabPosV = [2.3*shift 2*shift tableWidth  0.67*GUIHeight];
tab2ControlsH(5) = uitable('columnFormat',{'logical','char','char'},...
    'fontsize',10,'Data',{},'RowName',[],'ColumnName',...
    {'Select','Structure','Constraint'},'ColumnEditable',[true,false,false],...
    'BackgroundColor',[1 1 1],'Position',tabPosV,'ColumnWidth',...
    {tableWidth/8,tableWidth/4,5*tableWidth/8},'CellEditCallback',...
    @(hObj,hEvt)dispSelCriteriaROE(hObj,hEvt,hFig),'Visible','Off');

ud.ConstraintsInit = 0;


%% ------------------------  PLOT AXES -----------------------------------

%Axes
%NTCP vs TCP/BED
plotPosV = [leftMarginWidth+.175*GUIWidth 9*shift .775*GUIWidth-...
    leftMarginWidth GUIHeight-topMarginHeight-0.14*GUIHeight];

plotH(1) = axes('parent',hFig,'tag','modelsAxis','tickdir', 'out',...
    'nextplot','add','units','pixels','Position',plotPosV,'color',[1 1 1],...
    'XAxisLocation','bottom','YAxisLocation','left','xlim',[50 51],'ylim',[0 1],...
    'fontSize',9,'fontWeight','bold','box','on','visible','off');


%NTCP vs. scaled frx size
plotH(2) = axes('parent',hFig,'tag','modelsAxis','tickdir', 'out',...
    'nextplot','add','units','pixels','Position',plotPosV,'color',[1 1 1],...
    'XAxisLocation','bottom','YAxisLocation','left','xlim',[.5 1.5],...
    'ylim',[0 1],'fontSize',9,'fontWeight','bold','box','on','visible','off');
%TCP/BED vs. scaled frx size
plotH(3) = axes('parent',hFig,'tag','modelsAxis2','tickdir', 'out',...
    'nextplot','add','units','pixels','Position',plotPosV,'color','none',...
    'XAxisLocation','bottom','YAxisLocation','right','xlim',[.5 1.5],...
    'ylim',[0 1],'xtick',[],'fontSize',9,'fontWeight','bold','box','on',...
    'visible','off');


%NTCP vs. scaled nfrx
plotH(4) = axes('parent',hFig,'tag','modelsAxis','tickdir', 'out',...
    'nextplot','add','units','pixels','Position',plotPosV,'color',[1 1 1],...
    'XAxisLocation','bottom','YAxisLocation','left','ylim',[0 1],...
    'fontSize',9,'fontWeight','bold','box','on','visible','off');
%TCP/BED vs. scaled nfrx
plotH(5) = axes('parent',hFig,'tag','modelsAxis2','tickdir', 'out',...
    'nextplot','add','units','pixels','Position',plotPosV,'color','none',...
    'XAxisLocation','bottom','YAxisLocation','right',...
    'ylim',[0 1],'xtick',[],'fontSize',9,'fontWeight',...
    'bold','box','on','visible','off');


%Sliders
%scale frx size
plotH(6) = uicontrol('parent',hFig,'units','pixels','Position',...
    [leftMarginWidth+.18*GUIWidth 2*shift .75*GUIWidth-leftMarginWidth 1.8*shift],...
    'Style','Slider','Visible','Off','Tag','Scale','Min',0.5,'Max',1.5,'Value',1,...
    'SliderStep',[1/(99-1),1/(99-1)]);
addlistener(plotH(6),'ContinuousValueChange',...
    @(hObj,hEvt)scaleDoseROE(hObj,hEvt,hFig));
%scale nfrx
plotH(7) = uicontrol('parent',hFig,'units','pixels','Position',...
    [leftMarginWidth+.18*GUIWidth 2*shift .75*GUIWidth-leftMarginWidth 1.8*shift],...
    'Style','Slider','Visible','Off','Tag','Scale','Min',-15,'Max',15,'Value',0,...
    'SliderStep',[1/30 1/30]);
addlistener(plotH(7),'ContinuousValueChange',...
    @(hObj,hEvt)scaleDoseROE(hObj,hEvt,hFig));


%Push-button for constraints panel (decomissioned)
% plotH(8) = uicontrol('parent',hFig,'units','pixels','Position',...
%     [GUIWidth-17*shift 1.5*shift 15*shift 3*shift],...
%     'Style','push','Enable','On','String','View constraints',...
%     'backgroundColor',[192 205 230]./255,'fontSize',10,...
%     'Callback',{@critPanel,'INIT'},'tooltip',['Push to select',...
%     ' constraints for display.']);

%Input scale factor
plotH(9) = uicontrol('parent',hFig,'units','pixels','Position',...
    [GUIWidth-6*shift 4.5*shift 2.5*shift 2*shift],...
    'Style','edit','Enable','Off','fontSize',10,'Callback',...
    @(hObj,hEvt)enterScaleROE(hObj,hEvt,hFig));
plotH(10) = uicontrol('parent',hFig,'units','pixels','Position',...
    [GUIWidth-8*shift 1.5*shift 6*shift 3*shift],'backgroundColor',defaultColor,...
    'Style','Text','Visible','Off','fontSize',8,'Callback',...
    @(hObj,hEvt)enterScaleROE(hObj,hEvt,hFig));

%Lock/allow repositioning of data labels
if isdeployed
    [I,map] = imread(fullfile(getCERRPath,'pics','Icons','lock.gif'),'gif');
else
    [I,map] = imread('lock.gif','gif');
end
lockImg = ind2rgb(I,map);
plotH(11) = uicontrol('parent',hFig,'units','pixels','Position',...
    [leftMarginWidth+.15*GUIWidth 5*shift 2*shift 2*shift],...
    'cdata',lockImg,'Style','toggle','Value',0,...
    'Visible','Off','fontSize',8,'tooltip',sprintf(['Toggle to move',...
    '\n/lock label position']),'Callback',...
    @(hObj,hEvt)moveLabelsROE(hObj,hEvt,hFig));

%View DVH summary window (TBD)
%plotH(12) = uicontrol('parent',hFig,'units','pixels','Position',...
%    [GUIWidth-2*leftMarginWidth GUIHeight/2 2*shift 2*shift],...
%    'Style','push','Value',0,'Visible','Off','fontSize',8,...
%    'tooltip','View DVH','Callback',...
%    @(hObj,hEvt)dvhDisplayROE('init',hFig,planC));

%--------------------------------------------------------------------------

%% Turn off datacursor mode
cursorMode = datacursormode(hFig);
cursorMode.removeAllDataCursors;
set(cursorMode, 'Enable','Off');

%% Store handles
ud.handle.inputH = inputH;
ud.handle.tab1H = tab1ControlsH;
ud.handle.tab2H = tab2ControlsH;

ud.handle.modelsAxis = plotH;
guidata(hFig,ud);


end