function createUIControlsROE(hFig,planC)
% createUIControlsROE.m
% Create UI controls for the ROE interface.
% AI 10/21/21

%global stateS

ud = guidata(hFig);

% Get GUI size, margins
leftMarginWidth = ud.FigSettings.leftMarginWidth;
topMarginHeight = ud.FigSettings.topMarginHeight;
GUIWidth = ud.FigSettings.GUIWidth;
GUIHeight = ud.FigSettings.GUIHeight;
scaleV = ud.FigSettings.charScale;

shiftV = [10,10]./scaleV;
defaultColor = ud.FigSettings.defaultColor;
figColor = ud.FigSettings.figColor;
posTop = GUIHeight-topMarginHeight;

sliderRangeV = ud.userScaleRange;
set(gcf,'Units','characters')

fontSize = ud.FigSettings.fontSize;
smFontSize = ud.FigSettings.smFontSize;
lgFontSize = ud.FigSettings.lgFontSize;

%Draw frames
inputH(1) = uicontrol(hFig,'tag','titleFrame','units','characters',...
    'Position',[shiftV(1) shiftV(2) leftMarginWidth+.12*GUIWidth,...
    GUIHeight-topMarginHeight-4.8*shiftV(2) ],'Style','frame',...
    'backgroundColor',defaultColor);
inputH(2) = axes('parent',hFig,'units','characters','Position',...
    [leftMarginWidth+.13*GUIWidth, shiftV(2),...
    GUIWidth-leftMarginWidth-.14*GUIWidth,...
    GUIHeight-topMarginHeight-1.2*shiftV(2)],'color',defaultColor,...
    'ytick',[],'xtick',[],'box','on');

%Create tabs
inputH(3) = uicontrol(hFig,'style','togglebutton','string','Settings',...
    'units','characters','position',[1.1*shiftV(1) GUIHeight-...
    topMarginHeight-3.9*shiftV(2) 8*shiftV(1) 3.5*shiftV(2)],'fontWeight',...
    'bold','fontSize',fontSize,'BackgroundColor',defaultColor,...
    'foregroundColor',[0 0 0],'HorizontalAlignment','left','callback',...
    @(hObj,hData)switchTabsROE(hObj,hData,hFig));

inputH(4) = uicontrol(hFig,'style','togglebutton','string','Constraints',...
    'units','characters','position',[9.2*shiftV(1) GUIHeight-...
    topMarginHeight-3.9*shiftV(2) 8*shiftV(1) 3.5*shiftV(2)],'fontWeight',...
    'bold','fontSize',fontSize,'BackgroundColor',[211 228 228]./255,...
    'foregroundColor',[0.5 0.5 0.5],'HorizontalAlignment','left','callback',...
    @(hObj,hData)switchTabsROE(hObj,hData,hFig),'units','characters');

inputH(5) = uicontrol(hFig,'units','characters',...
    'Position',[17.25*shiftV(1), GUIHeight-topMarginHeight-3.9*shiftV(2),...
    34.2*shiftV(1), 3.6*shiftV(2)],'Style','push','backgroundColor',...
    figColor,'enable','off');


%% ------- TAB-1: SETTINGS----------------------

%Display models for selected protocol
tab1ControlsH(1) = uicontrol(hFig,'tag','modelTitle','units','characters',...
    'Position',[2*shiftV(1) posTop-.16*GUIHeight .16*GUIWidth 2*shiftV(2)],...
    'String','','Style','text','fontSize',fontSize,'fontWeight', 'Bold',...
    'BackgroundColor',defaultColor,'HorizontalAlignment','left');
optS = opts4Exe('CERRoptions.json');
protPath = optS.ROEProtocolPath;
if contains(protPath,'getCERRPath')
    protPath = eval(protPath);
end
tab1ControlsH(2) = uicontrol(hFig,'tag','modelFileSelect','units',...
    'characters','Position',[2*shiftV(1), posTop-.12*GUIHeight, ...
    .16*GUIWidth, 3*shiftV(2)], 'String',['Select baseline ',...
    'fractionation'],'Style','push', 'fontSize',fontSize,'FontWeight',...
    'normal','BackgroundColor',defaultColor,'HorizontalAlignment',...
    'right','callback','ROE(''LOAD_MODELS'')','tooltip',...
    sprintf(['Push to select fractionation schedule.\n ',...
    'Reading from ',protPath,'.\n To read from a different location',...
    ', update ROEProtocolPath in CERRoptions.json']));


% Pop-up menus to select structures & dose plans
if ispc
ht = 2.4*shiftV(2);
elseif ismac
ht = 3.6*shiftV(2);
end
tablePosV = [.22*GUIWidth-2.5*shiftV(1) posTop-.14*GUIHeight ...
    .22*GUIWidth ht];
colWidth = tablePosV(3)*scaleV(1);
colWidthC = {0.5*colWidth - 1, 0.5*colWidth - 1};
tab1ControlsH(3) = uitable(hFig,'Tag','strSel','Enable','Off',...
    'ColumnName',[],'RowName',[],'Visible','Off','backgroundColor',...
    defaultColor,'ColumnWidth',colWidthC,'columnEditable',...
    [true,true],'Data',{'Select structure','List of structures'},...
    'FontSize',fontSize,'units','characters',...
    'cellEditCallback',@(hObj,hData)editParamsROE(hObj,hData,hFig,planC));
set(tab1ControlsH(3),'Position',tablePosV-[0 3.6*shiftV(2) 0 0],...
    'units','characters');
tab1ControlsH(4) = uitable(hFig,'Tag','doseSel','Enable','Off',...
    'ColumnName',[],'RowName',[],'Visible','Off','backgroundColor',...
    defaultColor,'columnEditable',[true,true],'FontSize',fontSize,'Data',...
    {'Select dose plan','List of plans'},'ColumnWidth',...
    colWidthC,'units','characters','cellEditCallback',...
    @(hObj,hData)editParamsROE(hObj,hData,hFig,planC));
set(tab1ControlsH(4),'Position',tablePosV,'units','characters');
%tab1ControlsH(3).Position(3:4) = tab1ControlsH(3).Extent(3:4);
%tab1ControlsH(4).Position(3:4) = tab1ControlsH(4).Extent(3:4);

% Tables to display & edit model parameters
%Title: Model parameters
tab1ControlsH(5) = uicontrol(hFig,'units','characters','Visible','Off',...
    'fontSize',fontSize,'Position',tablePosV + [0 -.12*GUIHeight 0 0 ],...
    'String','Model parameters','Style','text','FontWeight','Bold',...
    'HorizontalAlignment','Left','backgroundColor',defaultColor);
%Model name display
tab1ControlsH(6) = uicontrol(hFig,'units','characters','Visible','Off',...
    'String','','Position',tablePosV + [0 -.16*GUIHeight 0 shiftV(2) ],...
    'FontSize',fontSize,'Style','text','FontWeight','Bold',...
    'HorizontalAlignment','Left','backgroundColor',defaultColor,...
    'foregroundColor',[.6 0 0]);
%JSON content display table (temp decomissioned)
tab1ControlsH(7) = uitable(hFig,'Tag','fieldEdit','Enable','Off',...
    'ColumnName',{'Fields','Values'},'FontSize',fontSize,'RowName',[],...
    'Visible','Off','backgroundColor',defaultColor,'units','characters',...
    'ColumnWidth',{round(tablePosV(3)/2),round(tablePosV(3)/2)},...
    'columnEditable',[false,true],'backgroundcolor',[1 1 1],...
    'cellEditCallback',@(hObj,hData)editParamsROE(hObj,hData,hFig,planC));
set(tab1ControlsH(7),'Position',tablePosV + ...
    [0 -.73*GUIHeight 0 8*shiftV(2)],'units','characters');
% Push-buttons to save, plot, display style
%Save button
tab1ControlsH(8) = uicontrol(hFig,'units','characters','Tag','saveJson',...
    'Position',[.36*GUIWidth 1.5*shiftV(2) .06*GUIWidth 3*shiftV(2)],...
    'backgroundColor',defaultColor,'String','Save','Style','Push',...
    'fontSize',fontSize,'FontWeight','normal','Enable','Off',...
    'Callback','ROE(''SAVE_MODELS'' )','tooltip','Save changes to JSON');
%Plot button
tab1ControlsH(9) = uicontrol(hFig,'units','characters','Tag','plotButton',...
    'Position',[.29*GUIWidth 1.5*shiftV(2) .06*GUIWidth 3*shiftV(2)],...
    'backgroundColor',defaultColor,'String','Plot','Style','Push',...
    'fontSize',fontSize,'FontWeight','normal','Enable','Off',...
    'Callback','ROE(''PLOT_MODELS'' )','tooltip','Push to plot');
%Plot mode
tab1ControlsH(10) = uicontrol(hFig,'units','characters','Tag','switchPlot',...
    'Position',[.18*GUIWidth .1*shiftV(2) .1*GUIWidth 4*shiftV(2)],...
    'backgroundColor',[1 1 1],'String',{'--Display mode--',...
    'NTCP v.BED','NTCP v.TCP','Scale fraction size',...
    'Scale no. fractions' },'Style','popup', 'fontSize',fontSize,...
    'FontWeight','normal','Enable','On','Callback',@(hObj,hEvt)...
    setPlotModeROE(hObj,hEvt,hFig),'tooltip','Select plot axes.');

% Input prescribed dose
tab1ControlsH(11) = uicontrol('parent',hFig,'units','characters','Position',...
    [.22*GUIWidth-2*shiftV(1) posTop-.09*GUIHeight 10*shiftV(1),2*shiftV(2)],...
    'Style','Text','String','Prescribed Dose','fontSize',fontSize,...
    'backgroundColor',defaultColor);
tab1ControlsH(12) = uicontrol('parent',hFig,'units','characters','Position',...
    [.3*GUIWidth+2*shiftV(1) posTop-.09*GUIHeight 8*shiftV(1),2.5*shiftV(2)],...
    'Style','Edit','String','','Visible','On','fontSize',fontSize,...
    'Callback',@(hObj,hEvt)clearStoredDVHsROE(hObj,hEvt,hFig),...
    'tooltip','Input Rx (Gy) and press enter.');
tab1ControlsH(13) = uicontrol('parent',hFig,'units','characters','Position',...
    [.38*GUIWidth+shiftV(1) posTop-.09*GUIHeight 2*shiftV(1),2*shiftV(2)],...
    'Style','Text','String','Gy','fontSize',fontSize,...
    'backgroundColor',defaultColor);


%% ------------------------ TAB-2: CONSTRAINTS ---------------------------

% Buttons (prev/next) to view constraints in order of violation
titlePosV = [.14*GUIWidth posTop-15*shiftV(2) 20*shiftV(1) 2.4*shiftV(2)];

tab2ControlsH(1) = uicontrol(hFig,'units','characters',...
    'Position',titlePosV,'Style', 'text','string','View previous / next',...
    'FontSize',lgFontSize,'backgroundColor',defaultColor,...
    'Visible','Off');
tab2ControlsH(2) = uicontrol(hFig,'units','characters',...
    'Position',titlePosV-[0 0 18*shiftV(1) 0],'Style','push','string',...
    '<<','FontSize',lgFontSize,'FontWeight','Bold','backgroundColor',...
    defaultColor,'callback',{@dispCriteriaROE,hFig,'prev'}','Visible','Off');
tab2ControlsH(3) = uicontrol(hFig,'units','characters',...
    'Position',titlePosV-[-18*shiftV(1) 0 18*shiftV(1) 0],'Style','push',...
    'string','>>','FontSize',lgFontSize,'FontWeight','Bold',...
    'backgroundColor',defaultColor, ...
    'callback',{@dispCriteriaROE,hFig,'next'}','Visible','Off');
tab2ControlsH(4) = uicontrol(hFig,'units','characters',...
    'Position',titlePosV-[2*shiftV(1) -5*shiftV(2) -5*shiftV(1) 0],...
    'Style', 'text','string','Select constraints to display','FontSize',...
    lgFontSize,'FontWeight','Bold','backgroundColor',defaultColor,...
    'Visible','Off');

%Table for interactive selection of constraints to display
tableWidth = 0.4*GUIWidth;
colWidthC = {tableWidth*scaleV(1)/8,tableWidth*scaleV(1)/4,5*tableWidth*scaleV(1)/8};
tabPosV = [2.3*shiftV(1) 2*shiftV(2) tableWidth  0.67*GUIHeight];
tab2ControlsH(5) = uitable(hFig,'columnFormat',{'logical','char','char'},...
    'fontsize',fontSize,'Data',{},'RowName',[],'ColumnName',{'Select',...
    'Structure','Constraint'},'ColumnEditable',[true,false,false],...
    'BackgroundColor',[1 1 1],'ColumnWidth',colWidthC,...
    'units','characters','CellEditCallback',...
    @(hObj,hEvt)dispSelCriteriaROE(hObj,hEvt,hFig),'Visible','Off');
set(tab2ControlsH(5),'Position',tabPosV,'units','characters');

ud.ConstraintsInit = 0;

%% ------------------------  PLOT AXES -----------------------------------

%Axes
%NTCP vs TCP/BED
plotPosV = [leftMarginWidth+.175*GUIWidth 9*shiftV(2) .775*GUIWidth-...
    leftMarginWidth GUIHeight-topMarginHeight-0.14*GUIHeight];

plotH(1) = axes('parent',hFig,'tag','modelsAxis','tickdir', 'out',...
    'nextplot','add','units','characters','Position',plotPosV,'color',...
    [1 1 1],'XAxisLocation','bottom','YAxisLocation','left','xlim',...
    [50 51],'ylim',[0 1],'fontSize',smFontSize,'fontWeight','bold',...
    'box','on','visible','off');


%NTCP vs. scaled frx size
plotH(2) = axes('parent',hFig,'tag','modelsAxis','tickdir', 'out',...
    'nextplot','add','units','characters','Position',plotPosV,'color',...
    [1 1 1],'XAxisLocation','bottom','YAxisLocation','left','xlim',...
    sliderRangeV,'ylim',[0 1],'fontSize',smFontSize,'fontWeight',...
    'bold','box','on','visible','off');
%TCP/BED vs. scaled frx size
plotH(3) = axes('parent',hFig,'tag','modelsAxis2','tickdir', 'out',...
    'nextplot','add','units','characters','Position',plotPosV,'color','none',...
    'XAxisLocation','bottom','YAxisLocation','right','xlim',sliderRangeV,...
    'ylim',[0 1],'xtick',[],'fontSize',smFontSize,'fontWeight','bold',...
    'box','on','visible','off');


%NTCP vs. scaled nfrx
plotH(4) = axes('parent',hFig,'tag','modelsAxis','tickdir', 'out',...
    'nextplot','add','units','characters','Position',plotPosV,'color',...
    [1 1 1],'XAxisLocation','bottom','YAxisLocation','left','ylim',[0 1],...
    'fontSize',smFontSize,'fontWeight','bold','box','on','visible','off');
%TCP/BED vs. scaled nfrx
plotH(5) = axes('parent',hFig,'tag','modelsAxis2','tickdir', 'out',...
    'nextplot','add','units','characters','Position',plotPosV,'color','none',...
    'XAxisLocation','bottom','YAxisLocation','right',...
    'ylim',[0 1],'xtick',[],'fontSize',smFontSize,'fontWeight',...
    'bold','box','on','visible','off');


%Sliders
%scale frx size
plotH(6) = uicontrol('parent',hFig,'units','characters','Position',...
    [leftMarginWidth+.18*GUIWidth 2*shiftV(2), ...
    .75*GUIWidth-leftMarginWidth 1.8*shiftV(2)],'Style','Slider',...
    'Visible','Off','Tag','Scale','Min',sliderRangeV(1),...
    'Max',sliderRangeV(2),'Value',1,'SliderStep',[1/(99-1),1/(99-1)]);
addlistener(plotH(6),'ContinuousValueChange',...
    @(hObj,hEvt)scaleDoseROE(hObj,hEvt,hFig));
%scale nfrx
plotH(7) = uicontrol('parent',hFig,'units','characters','Position',...
    [leftMarginWidth+.18*GUIWidth 2*shiftV(2), ...
    .75*GUIWidth-leftMarginWidth 1.8*shiftV(2)],'Style','Slider',...
    'Visible','Off','Tag','Scale','Min',-15,'Max',15,'Value',0,...
    'SliderStep',[1/30 1/30]);
addlistener(plotH(7),'ContinuousValueChange',...
    @(hObj,hEvt)scaleDoseROE(hObj,hEvt,hFig));


%Push-button for constraints panel (decomissioned)
% plotH(8) = uicontrol('parent',hFig,'units','pixels','Position',...
%     [GUIWidth-17*shift 1.5*shift 15*shift 3*shift],...
%     'Style','push','Enable','On','String','View constraints',...
%     'backgroundColor',[192 205 230]./255,'fontSize',10,...
%     'Callback',{@critPanel,'INIT'},'tooltip',['Push to select',...
%     ' constraints for display.']);

%Input scale factor
plotH(9) = uicontrol('parent',hFig,'units','characters','Position',...
    [GUIWidth-6*shiftV(1) 4.5*shiftV(2) 2.5*shiftV(1) 2*shiftV(2)],...
    'Style','edit','Enable','Off','fontSize',fontSize,'Callback',...
    @(hObj,hEvt)enterScaleROE(hObj,hEvt,hFig));
plotH(10) = uicontrol('parent',hFig,'units','characters','Position',...
    [GUIWidth-8*shiftV(1) 1.5*shiftV(2) 6*shiftV(1) 3*shiftV(2)],...
    'backgroundColor',defaultColor,'Style','Text','Visible','Off',...
    'fontSize',fontSize,'Callback',@(hObj,hEvt)enterScaleROE(hObj,hEvt,hFig));

%Lock/allow repositioning of data labels
if isdeployed
    [I,map] = imread(fullfile(getCERRPath,'pics','Icons','lock.gif'),'gif');
else
    [I,map] = imread('lock.gif','gif');
end
lockImg = ind2rgb(I,map);
plotH(11) = uicontrol('parent',hFig,'units','characters','Position',...
    [leftMarginWidth+.15*GUIWidth 5*shiftV(2) 2*shiftV(1) 2*shiftV(2)],...
    'cdata',lockImg,'Style','toggle','Value',0,'Visible','Off',...
    'fontSize',fontSize,'tooltip',sprintf(['Toggle to move',...
    '\n/lock label position']),'Callback',...
    @(hObj,hEvt)moveLabelsROE(hObj,hEvt,hFig));

%View DVH summary window (TBD)
%plotH(12) = uicontrol('parent',hFig,'units','pixels','Position',...
%    [GUIWidth-2*leftMarginWidth GUIHeight/2 2*shift 2*shift],...
%    'Style','push','Value',0,'Visible','Off','fontSize',8,...
%    'tooltip','View DVH','Callback',...
%    @(hObj,hEvt)dvhDisplayROE('init',hFig,planC));

%--------------------------------------------------------------------------

%% Turn off datacursor mode
cursorMode = datacursormode(hFig);
cursorMode.removeAllDataCursors;
set(cursorMode, 'Enable','Off');

%% Store handles
ud.handle.inputH = inputH;
ud.handle.tab1H = tab1ControlsH;
ud.handle.tab2H = tab2ControlsH;

ud.handle.modelsAxis = plotH;
guidata(hFig,ud);


end