function anonDigitalFilmS = defineAnonDigitalfilm()
%
% function anonDigitalFilmS = defineAnonDigitalfilm()
%
% Defines the anonymous "digitalFilm" data structure. The fields containing PHI have
% been left out by default. In order to leave out additional fields, remove
% them from the list below. 
%
% The following three operations are allowed per field of the input data structure:
% 1. Keep the value as is: listed as 'keep' in the list below.
% 2. Allow only the specific values: permitted values listed within a cell array. 
%    If no match is found, a default anonymous string will be inserted.
% 3. Insert dummy date: listed as 'date' in the list below. Date will be
%    replaced by a dummy value of 11/11/1111.
%
% APA, 1/11/2018

anonDigitalFilmS = struct( ...
    'imageNumber',  'keep', ...
    'imageType',  'keep', ...
    'beamNumber',  'keep', ...
    'beamDescription',  'keep', ...
    'filmNumber',  'keep', ...
    'filmDate',  'date', ...
    'filmType',  'keep', ...
    'filmSource',  'keep', ...
    'numberOfDimensions',  'keep', ...
    'sizeOfDimension1',  'keep', ...
    'sizeOfDimension2',  'keep', ...
    'grid1Units',  'keep', ...
    'grid2Units',  'keep', ...
    'sourceImageDistance',  'keep', ...
    'xOffset',  'keep', ...
    'yOffset',  'keep', ...
    'bytesPerPixel',  'keep', ...
    'numberRepresentation',  'keep', ...
    'unitNumber',  'keep', ...
    'ODScale',  'keep', ...
    'bitsPerPixel',  'keep', ...
    'collimatorAngle',  'keep', ...
    'image',  'keep' ...
           );
