function CreateVersorPanel(handles)
%
% Copyright 2010, Joseph O. Deasy, on behalf of the CERR development team.
% 
% This file is part of The Computational Environment for Radiotherapy Research (CERR).
% 
% CERR development has been led by:  Aditya Apte, Divya Khullar, James Alaly, and Joseph O. Deasy.
% 
% CERR has been financially supported by the US National Institutes of Health under multiple grants.
% 
% CERR is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of CERR is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% CERR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with CERR.  If not, see <http://www.gnu.org/licenses/>.

    %Versor Panel
    handles.versorPanel = uipanel('Parent',handles.toolPanel,'Units','normalize','FontSize',10,'Title','Registration Parameters',...
                                    'Tag','versorPanel','Clipping','off',...
                                    'Position',[0 0 1 1],...
                                    'Visible','on');
    dx = 20; dy = 60;          
    h219 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[15+dx 116.375+dy 110 15.7777777777778],...
    'String','Optimizer Scale X:',...
    'Style','text',...
    'Tag','text13');

    handles.versor_s_x = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[131.961538461539+dx 112.430555555556+dy 87.3076923076924 23.6666666666667],...
    'String','1.0',...
    'Style','edit',...
    'Tag','versor_s_x');

    h226 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[15+dx 85.0408163265306+dy 110 15.4557823129252],...
    'String','Optimizer Scale Y:',...
    'Style','text',...
    'Tag','text14');

    handles.versor_s_y = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[131.961538461539+dx 78.9027777777778+dy 87.3076923076924 25.6388888888889],...
    'String','1.0',...
    'Style','edit',...
    'Tag','versor_s_y');

    h222 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[15+dx 54.25+dy 110 15.7777777777778],...
    'String','Optimizer Scale Z:',...
    'Style','text',...
    'Tag','text15');

    handles.versor_s_z = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[131.961538461539+dx 48.3333333333333+dy 87.3076923076924 23.6666666666667],...
    'String','1.0',...
    'Style','edit',...
    'Tag','versor_s_z');

    h224 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[5.36538461538462+dx 16.7777777777778+dy 118.956730769231 23.6666666666667],...
    'String',' TranslationScale:',...
    'Style','text',...
    'Tag','text42');

    handles.versor_s_t = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[131.961538461539+dx 14.8055555555556+dy 87.3076923076924 23.6666666666667],...
    'String','0.001',...
    'Style','edit',...
    'Tag','versor_s_t');

    

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    dx = 21; dy = 200;
    h328 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[9+dx 90+dy 118 17],...
    'String','Minimum Step:',...
    'Style','text',...
    'Tag','text16');

    handles.versor_i_minstep = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[135+dx 88+dy 79 21],...
    'String','0.01',...
    'Style','edit',...
    'Tag','versor_i_minstep');

    h329 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[9+dx 59+dy 118 17],...
    'String','Maximum Step:',...
    'Style','text',...
    'Tag','text17');

    handles.versor_i_maxstep = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[135+dx 58+dy 79 22],...
    'String','1.2',...
    'Style','edit',...
    'Tag','versor_i_maxstep');

    h332 = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','right',...
    'Position',[9+dx 28+dy 118 17],...
    'String','Iteration Number :',...
    'Style','text',...
    'Tag','text18');

    handles.versor_i_num = uicontrol(...
    'Parent',handles.versorPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[135+dx 28+dy 79 21],...
    'String','200',...
    'Style','edit',...
    'Tag','versor_i_num');


    guidata(handles.mainframe, handles);

end