function CreateOptimizerPanel(handles)
%
% Copyright 2010, Joseph O. Deasy, on behalf of the CERR development team.
% 
% This file is part of The Computational Environment for Radiotherapy Research (CERR).
% 
% CERR development has been led by:  Aditya Apte, Divya Khullar, James Alaly, and Joseph O. Deasy.
% 
% CERR has been financially supported by the US National Institutes of Health under multiple grants.
% 
% CERR is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of CERR is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% CERR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with CERR.  If not, see <http://www.gnu.org/licenses/>.

%general Optimizer Panel
    handles.optimizerPanel = uipanel('Parent',handles.toolPanel,'Units','normalize','FontSize',9,'Title','Registration Parameters',...
                                    'Tag','optimizerPanel','Clipping','off',...
                                    'Position',[0 0 1 1],...
                                    'Visible','on');
    dy = 200;
    h321 = uicontrol(...
    'Parent',handles.optimizerPanel,...
    'Units','pixel',...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[9 dy+90 118 17],...
    'String','Minimum Step:',...
    'Style','text',...
    'Tag','optimizerPanel');

    h322 = uicontrol(...
    'Parent',handles.optimizerPanel,...
    'Units','pixel',...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[9 dy+59 118 17],...
    'String','Maximum Step:',...
    'Style','text',...
    'Tag','optimizerPanel');

    handles.para.minstep = uicontrol(...
    'Parent',handles.optimizerPanel,...
    'Units','pixel',...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[130 dy+86 79 21],...
    'String','0.01',...
    'Style','edit',...
    'Tag','optimizerPanel');

    handles.para.maxstep = uicontrol(...
    'Parent',handles.optimizerPanel,...
    'Units','pixel',...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[130 dy+55 79 22],...
    'String','4',...
    'Style','edit',...
    'Tag','optimizerPanel');

    h325 = uicontrol(...
    'Parent',handles.optimizerPanel,...
    'Units','pixel',...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[9 dy+28 118 17],...
    'String','Iteration Number :',...
    'Style','text',...
    'Tag','optimizerPanel');

    handles.para.iternum = uicontrol(...
    'Parent',handles.optimizerPanel,...
    'Units','pixel',...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[130 dy+24 79 21],...
    'String','200',...
    'Style','edit',...
    'Tag','optimizerPanel');

    guidata(handles.mainframe, handles);
    
end

