function CreateOpticalFlowPanel(handles)
%
% Copyright 2010, Joseph O. Deasy, on behalf of the CERR development team.
% 
% This file is part of The Computational Environment for Radiotherapy Research (CERR).
% 
% CERR development has been led by:  Aditya Apte, Divya Khullar, James Alaly, and Joseph O. Deasy.
% 
% CERR has been financially supported by the US National Institutes of Health under multiple grants.
% 
% CERR is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of CERR is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% CERR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with CERR.  If not, see <http://www.gnu.org/licenses/>.


    %demonss Panel
    handles.opticalFlowPanel = uipanel('Parent',handles.toolPanel,'Units','normalize','FontSize',10,'Title','Optical Flow methods',...
                                    'Tag','opticalFlowPanel','Clipping','off',...
                                    'Position',[0 0 1 1],...
                                    'Visible','on');
    dx = 20; dy = 60;                                
    h305 = uicontrol(...
    'Parent',handles.opticalFlowPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[10.1923076923077+dx 214.208333333333+dy 60.649038461538 21.8472222222222],...
    'String','Methods:',...
    'Style','text');

    handles.para.optFlowMethod = uicontrol(...
    'Parent',handles.opticalFlowPanel,...
    'FontSize',10, 'backgroundcolor', [.65 .79 .94], ...
    'Position',[90.884615384615+dx 215.215277777778+dy 260.9230769230769 23.8333333333333],...
    'String',{ 'Horn-Schunck original method'; 'Lucas and Kanade local LMS method'; 'Levelset motion method'; ...
               'Horn-Schunck original + intensity correction method'; 'Inverse consistency Horn-Schunck'; ... 
               'Inverse consistency Horn-Schunck with image intensity correction'; ...
               'Demons Methods'; ...
               'Modified Demons Methods'},...
    'Style','popupmenu',...
    'CallBack', '', ...
    'Value',1);

    h306 = uicontrol(...
    'Parent',handles.opticalFlowPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[10.1923076923077+dx 185.4097222222222+dy 120.8173076923077 15.8888888888889],...
    'String','Registration Levels:',...
    'Style','text');

    
    handles.para.optFlowRegistLevel = uicontrol(...
    'Parent',handles.opticalFlowPanel,...
    'FontSize',10,...
    'HorizontalAlignment','left',...
    'Position',[150.884615384615+dx 179.4513888888889+dy 26 25.8194444444444],...
    'String','3',...
    'Style','edit');

    
    guidata(handles.mainframe, handles);
    
end

    