function Initializeco_reggui()
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Initialization graphics for co_reggui (co-registration tool)
% Written By: Issam El Naqa    Date: 08/28/03
% Revised by:                  Date:  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Copyright 2010, Joseph O. Deasy, on behalf of the CERR development team.
% 
% This file is part of The Computational Environment for Radiotherapy Research (CERR).
% 
% CERR development has been led by:  Aditya Apte, Divya Khullar, James Alaly, and Joseph O. Deasy.
% 
% CERR has been financially supported by the US National Institutes of Health under multiple grants.
% 
% CERR is distributed under the terms of the Lesser GNU Public License. 
% 
%     This version of CERR is free software: you can redistribute it and/or modify
%     it under the terms of the GNU General Public License as published by
%     the Free Software Foundation, either version 3 of the License, or
%     (at your option) any later version.
% 
% CERR is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
% without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% See the GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with CERR.  If not, see <http://www.gnu.org/licenses/>.

%getclusterinfo;
%mycolors;
nndkgray = [0.3 0.3 0.3];
nnltgray = [0.8 0.8 0.8];
nnred = [0.8 0.0 0.0];
%Main figure window
h0 = figure('Color',[0.8 0.8 0.8], ...
   'Colormap',gray(256), ...
   'FileName','', ...
   'Name','Co-registration GUI', ...
   'NumberTitle','off', ...
   'PaperPosition',[18 180 576 432], ...
   'PaperUnits','normalized', ...
   'Position',[20 40 988 700], ...
   'Resize','off',...
   'ShareColors','off',...
   'Tag','Fig1', ...
   'ToolBar','none','MenuBar', 'none');
h1 = uicontrol('Parent',h0, ...
   'BackgroundColor',nndkgray, ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[746 5 176 67], ...
   'Style','frame', ...
   'Tag','Frame1');
h1 = uicontrol('Parent',h0, ...
   'BackgroundColor',nndkgray, ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[364 99 248 145], ...
   'Style','frame', ...
   'Tag','Frame2');
h1 = uicontrol('Parent',h0, ...
   'Callback','co_reggui(''close'')', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[758 9 154 22], ...
   'String','Close', ...
   'Tag','Pushbutton1');
h1 = uicontrol('Parent',h0, ...
   'Callback','helpwin co_reggui', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[758 39 154 22], ...
   'String','Info', ...
   'Tag','Pushbutton2');

%%%% reference image axis %%%
h1 = axes('Parent',h0, ...
    'Box','on', ...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',nnltgray, ...
    'FontSize',8, ...
    'Position',[0.023 0.54 0.22 0.317], ...
    'Tag','axref', ...
    'NextPlot','add', ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);

h1 = uicontrol('Parent',h0, ...
   'Callback','co_reggui(''LoadRefImage'')', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[49 620 152 30], ...
   'String','Load Reference Image', ...
   'Tag','loadregpushbutton');

h1 = uicontrol('Parent',h0, ...
   'Callback','co_reggui(''LoadPlanCRefImage'')', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[202 620 49 30], ...
   'String','planC', ...
   'Tag','loadplanCrefpushbutton');

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[13.6 46.231 22.4 1.308], ...
   'String','Reference Image', ...
   'Style','text', ...
   'Tag','reftext');

%%%% unregistered image axis %%%
h1 = axes('Parent',h0, ...
    'Box','on', ...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',nnltgray, ...
    'FontSize',8, ...
    'Position',[0.023 0.126 0.22 0.32], ...
    'Tag','axunreg', ...
    'NextPlot','add', ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
   'Callback','co_reggui(''LoadUnregImage'')', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[49 329 152 30], ...
   'String','Load Unregistered Image', ...
   'Tag','loadunregpushbutton');

h1 = uicontrol('Parent',h0, ...
   'Callback','co_reggui(''LoadPlanCUnregImage'')', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[202 329 49 30], ...
   'String','planC', ...
   'Tag','loadplanCunregpushbutton');

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[13.6 24 22.4 1.308], ...
   'String','Unregistered Image', ...
   'Style','text', ...
   'Tag','unregtext');

%%%% joint histogram axis %%%
h1 = axes('Parent',h0, ...
    'Box','on', ...
    'CameraUpVector',[0 0 1], ...
    'CameraUpVectorMode','auto', ...
    'Color',nnltgray, ...
    'FontSize',8, ...
    'Position',[0.725 0.5 0.22 0.316], ...
    'Tag','axjhist', ...
    'NextPlot','add', ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
     'ZColor',[0 0 0],...
     'ZTickMode','manual');

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[152.2 43.9 22.4 1.308], ...
   'String','Joint Histogram', ...
   'Style','text', ...
   'Tag','jhisttext');

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'ForegroundColor',nnred, ...
   'FontSize',9.0,...
   'FontWeight','bold',...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[128.2 45.5 26 1.231], ...
   'String','Mutual Information =', ...
   'Style','text', ...
   'Tag','mitext',...
   'Visible','on');

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[153.8 45.4 9.2 1.462], ...
   'String','', ...
   'Style','text', ...
   'Tag','mivalue');
%%%% cross correlation axis %%%
h1 = axes('Parent',h0, ...
    'Box','on', ...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',nnltgray, ...
    'FontSize',8, ...
    'Position',[0.725 0.143 0.22 0.316], ...
    'Tag','axcorr', ...
    'NextPlot','add', ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[152.2 24.7 22.4 1.308], ...
   'String','Cross Correlation', ...
   'Style','text', ...
   'Tag','jxcorrtext');

%%%% Registered image axis %%%
h1 = axes('Parent',h0, ...
    'Box','on', ...
    'CameraUpVector',[0 1 0], ...
    'CameraUpVectorMode','manual', ...
    'Color',nnltgray, ...
    'FontSize',8, ...
    'Position',[0.365 0.45 0.256 0.404], ...
    'Tag','axreg', ...
    'NextPlot','add', ...
    'XColor',[0 0 0], ...
    'XTickMode','manual', ...
    'YColor',[0 0 0], ...
    'YTickMode','manual', ...
    'ZColor',[0 0 0]);
h1 = uicontrol('Parent',h0, ...
   'Callback','co_reggui(''ApplyRegistration'')', ...
   'Interruptible','off', ...
   'FontSize',10.0,...
   'FontWeight','bold',...
   'ListboxTop',0, ...
   'Position',[361 600 151 51], ...
   'String','REGISTER', ...
   'Tag','regpushbutton',...
   'Enable','on');
h1 = uicontrol('Parent',h0, ...
	'Units','characters', ...
	'BackgroundColor',nnltgray, ...
	'Callback','co_reggui(''DisplayMode'')', ...
	'ListboxTop',0, ...
	'Position',[102.4 46 20.6 1.769], ...
	'String','Single registered|Overlayed images|Sliceomatic', ...
    'Style','popupmenu', ...
    'TooltipString','Input display mode', ...
	'Tag','dispmodepopupmenu', ...
	'Value',1,...
    'Enable','on');

h1 = uicontrol('Parent',h0, ...
	'Units','characters', ...
	'BackgroundColor',nnltgray, ...
	'Callback','co_reggui(''RegisterMode'')', ...
	'ListboxTop',0, ...
	'Position',[72.5 19.75 50 2], ...
	'String','Manual|Control Points (Affine)|Control Points (Perspective)|Auto Control Points', ...
    'Style','popupmenu', ...
    'TooltipString','Input Register mode', ...
	'Tag','dispregpopupmenu', ...
	'Value',1,...
    'Enable','on');

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'HorizontalAlignment','center', ...
   'Interruptible','off', ...
   'ListboxTop',0, ...
   'Position',[102.2 48 20.2 1.154], ...
   'String','Display mode', ...
   'Style','text', ...
   'Tag','jdispmode');
%%%% registration parameters  %%%%
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[72.6 18.462 49.6 1.538], ...
   'String','Registration parameters', ...
   'Style','text', ...
   'Tag','regparamtext');
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[73.8 16.231 11.8 1.154], ...
   'String','Translation:', ...
   'Style','text', ...
   'Tag','transtext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.444 0.296 0.037 0.029], ...
   'String','0.0', ...
   'Style','edit', ...
   'Tag','TXed', ...
   'UserData',0.0);
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[89.4 17.308 4 1.1231], ...
   'String','x', ...
   'Style','text', ...
   'Tag','TXtext');
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[100.4 17.308 4 1.1231], ...
   'String','y', ...
   'Style','text', ...
   'Tag','TYtext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.5 0.296 0.037 0.029], ...
   'String','0.0', ...
   'Style','edit', ...
   'Tag','TYed', ...
   'UserData',0.0);
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[111.2 17.308 4 1.1231], ...
   'String','z', ...
   'Style','text', ...
   'Tag','TZtext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.554 0.296 0.037 0.029], ...
   'String','0.0', ...
   'Style','edit', ...
   'Tag','TZed', ...
   'UserData',0.0);

h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[73 10.769 11 1.154], ...
   'String','Scaling:', ...
   'Style','text', ...
   'Tag','sctext');
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[89.4 11.923 4 1.1231], ...
   'String','x', ...
   'Style','text', ...
   'Tag','SXtext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.444 0.196 0.037 0.029], ...
   'String','1.0', ...
   'Style','edit', ...
   'Tag','SXed', ...
   'UserData',1.0);
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[100.8 12 4 1.1231], ...
   'String','y', ...
   'Style','text', ...
   'Tag','SYtext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.5 0.196 0.037 0.029], ...
   'String','1.0', ...
   'Style','edit', ...
   'Tag','SYed', ...
   'UserData',1.0);
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[111.6 12 4 1.1231], ...
   'String','z', ...
   'Style','text', ...
   'Tag','SZtext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.554 0.196 0.037 0.029], ...
   'String','1.0', ...
   'Style','edit', ...
   'Tag','SZed', ...
   'UserData',1.0);
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[72.8 13.538 11.8 1.154], ...
   'String','Rotation:', ...
   'Style','text', ...
   'Tag','rottext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.432 0.25 0.037 0.029], ...
   'String','0.0', ...
   'Style','edit', ...
   'Tag','Roted', ...
   'UserData',0.0);
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[94 13.61 4 1.1231], ...
   'String','deg', ...
   'Style','text', ...
   'Tag','degtext');
h1 = uicontrol('Parent',h0, ...
   'Units','characters', ...
   'BackgroundColor',nndkgray, ...
   'ForegroundColor',[1 1 1], ...
   'ListboxTop',0, ...
   'Position',[74.6 8.385 18 1.308], ...
   'String','Resampling factor:', ...
   'Style','text', ...
   'Tag','resamptext');
h1 = uicontrol('Parent',h0, ...
   'Units','normalized',...
   'BackgroundColor',[1 1 1], ...
   'Callback','co_reggui(''EditRegParam'')', ...
   'ListboxTop',0, ...
   'Position',[0.475 0.157 0.037 0.029], ...
   'String','1.0', ...
   'Style','edit', ...
   'Tag','Resamped', ...
   'UserData',1.0);

% status bar
uicontrol('Style', 'text',...
   'Tag', 'StatusText',...
   'Parent', h0, ...
   'BackgroundColor', [0.8 0.8 0.8], ...
   'ForegroundColor', [0 0 .8], ...
   'String', 'Select image(s) for registration...',...
   'Position',[390 10 215 20], ...
   'HorizontalAlignment', 'center');
% initial paramters
h.pathname=pwd;
h.displaymode=1;
h.Tx=str2num(get(findobj(gcf,'Tag','TXed'),'String'));
h.Ty=str2num(get(findobj(gcf,'Tag','TYed'),'String'));
h.Tz=str2num(get(findobj(gcf,'Tag','TZed'),'String'));
h.rot=str2num(get(findobj(gcf,'Tag','Roted'),'String'));
h.Sx=str2num(get(findobj(gcf,'Tag','SXed'),'String'));
h.Sy=str2num(get(findobj(gcf,'Tag','SYed'),'String'));
h.Sz=str2num(get(findobj(gcf,'Tag','SZed'),'String'));
h.samp=str2num(get(findobj(gcf,'Tag','Resamped'),'String'));
set(gcf,'UserData',h);
return